deployment:
  tasks:
    - name: Installer les dépendances
      command: npm install --prefix wp-theme-vite-tailwind-main
    - name: Construire le projet
      command: npm run build --prefix wp-theme-vite-tailwind-main
    - name: Déployer les fichiers
      command: |
        rsync -avz --exclude='node_modules' --exclude='wp-theme-vite-tailwind-main/src' wp-theme-vite-tailwind-main/ /home/username/public_html/
